name: Release

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "0 0 * * *"
on: [push]

jobs:    

  All:
    
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [macos] # , ubuntu, windows
        arch: [x64] # x86, x64, arm64, armv6l, armv7l, ppc64le, s390x

    steps:
      - name: init
        uses: actions/checkout@v2
        
      - name: install brew
        run: |
          brew install rpm
        shell: bash

      - name: get sha
        id: sha
        shell: bash
        run: echo "::set-output name=value::$(cat sha.txt)"

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}}
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone ${{secrets.GIT_ADDRESS}} .
          git checkout $sha
        shell: bash
      
      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # architecture: ${{ matrix.arch }}
          check-latest: true
      
      - name: install
        run: npm i
        shell: bash
      
      - name: build
        run: npm run build
        shell: bash
        
      - name: ls
        run: |
          cd build
          ls -alF
        shell: bash
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ./build/Clashr*
