name: Release

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "0 0 * * *"
on: [push]

jobs:    

  Test:
    
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64, arm64] # x86, x64, arm64, armv6l, armv7l, ppc64le, s390x

    steps:
      - name: init
        uses: actions/checkout@v2

      - name: get sha
        id: sha
        shell: bash
        run: echo "::set-output name=value::$(cat sha.txt)"

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}}
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone ${{secrets.GIT_ADDRESS}} .
          git checkout $sha
        shell: bash
      
      - name: set go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.2
      
      - name: set GO111MODULE
        run: |
          go help env
          go env -w GO111MODULE="on"
          go env
        shell: bash
      
      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
          check-latest: true
      
      - name: install
        run: pm i
        shell: bash
      
#       - name: install electron-builder with macos latest
#         if: startsWith(matrix.os, 'macOS')
#         run: npm i electron-builder@21.2.0
      
      - name: build
        run: npm run build
        shell: bash
